import type { Thread } from '../types';

export const DEFAULT_THREADS: Thread[] = [
  {
    id: 'social',
    name: 'Social',
    unit: 'minutes',
    weeklyGoal: 300,
    color: '#EC4899',
    defaultAmount: 60,
    icon: '◐',
    aliases: [
      'friends', 'friend', 'family', 'hangout', 'hang out', 'hanged out',
      'hung out', 'coffee with', 'coffee w', 'dinner with', 'dinner w',
      'lunch with', 'lunch w', 'brunch with', 'brunch w', 'party', 'partied',
      'social', 'met up', 'meetup', 'meet up', 'drinks with', 'drinks w',
      'date', 'chatted', 'called', 'facetimed', 'texted a friend', 'sister',
      'brother', 'mom', 'dad', 'parents', 'roommate', 'roommates',
      'friend group', 'gf', 'girlfriend', 'bf', 'boyfriend',
    ],
  },
  {
    id: 'classes',
    name: 'Classes',
    unit: 'minutes',
    weeklyGoal: 900,
    color: '#3B82F6',
    defaultAmount: 60,
    icon: '◒',
    aliases: [
      'class', 'classes', 'lecture', 'lectures', 'seminar', 'section',
      'tutorial', 'studied', 'studying', 'study session', 'homework', 'hw',
      'assignment', 'assignments', 'reading', 'course', 'coursework',
      'discussion', 'lab', 'labs', 'attended class', 'went to class',
    ],
  },
  {
    id: 'leetcode',
    name: 'LeetCode',
    unit: 'count',
    weeklyGoal: 14,
    color: '#F59E0B',
    defaultAmount: 1,
    icon: '◑',
    aliases: [
      'leetcode', 'lc', 'coding problem', 'coding problems', 'problem',
      'problems', 'algorithm', 'algorithms', 'algo', 'algos', 'dsa',
      'data structures', 'neetcode', 'codeforces', 'hackerrank',
    ],
  },
  {
    id: 'jobs',
    name: 'Job Apps',
    unit: 'count',
    weeklyGoal: 25,
    color: '#8B5CF6',
    defaultAmount: 1,
    icon: '◓',
    aliases: [
      'job', 'jobs', 'application', 'applications', 'apps', 'applied',
      'apply', 'submitted app', 'submitted apps', 'cover letter',
      'cover letters', 'resume', 'referral', 'referrals', 'linkedin',
      'reached out', 'recruiter', 'interview', 'interviews',
    ],
  },
  {
    id: 'clubs',
    name: 'Clubs',
    unit: 'minutes',
    weeklyGoal: 180,
    color: '#22C55E',
    defaultAmount: 60,
    icon: '◔',
    aliases: [
      'club', 'clubs', 'meeting', 'meetings', 'org', 'organization',
      'society', 'chapter', 'exec', 'board meeting', 'general body',
      'gbm', 'volunteer', 'volunteering',
    ],
  },
  {
    id: 'cooking',
    name: 'Cooking',
    unit: 'count',
    weeklyGoal: 7,
    color: '#F97316',
    defaultAmount: 1,
    icon: '◕',
    aliases: [
      'cooked', 'cooking', 'cook', 'meal', 'meals', 'dinner', 'lunch',
      'breakfast', 'made pasta', 'made', 'baked', 'baking', 'prepped',
      'meal prep', 'meal prepped', 'made food', 'stir fry', 'stir fried',
      'grilled', 'roasted', 'sautéed', 'sauteed', 'ate at home',
      'cooked at home',
    ],
  },
  {
    id: 'personal',
    name: 'Personal',
    unit: 'count',
    weeklyGoal: 7,
    color: '#94A3B8',
    defaultAmount: 1,
    icon: '◍',
    aliases: [
      'cleaning', 'cleaned', 'laundry', 'dishes', 'groceries', 'grocery',
      'errand', 'errands', 'chore', 'chores', 'tidied', 'tidy', 'vacuumed',
      'vacuum', 'organized', 'organize', 'shopping', 'personal', 'self-care',
      'self care', 'meditation', 'meditated', 'journaled', 'journaling',
      'reading', 'read a book', 'took out trash', 'shower', 'skincare',
      'walked', 'nap', 'napped',
    ],
  },
  {
    id: 'coursework',
    name: 'Coursework',
    unit: 'count',
    weeklyGoal: 5,
    color: '#0EA5A3',
    defaultAmount: 1,
    icon: '◈',
    aliases: [
      'assignment', 'assignments', 'hw', 'homework', 'problem set',
      'pset', 'project', 'essay', 'paper', 'exam', 'midterm', 'final',
      'quiz', 'submitted', 'turned in', 'finished assignment',
    ],
  },
  {
    id: 'workout',
    name: 'Working Out',
    unit: 'minutes',
    weeklyGoal: 240,
    color: '#EF4444',
    defaultAmount: 45,
    icon: '●',
    aliases: [
      'gym', 'workout', 'worked out', 'work out', 'working out',
      'exercise', 'exercised', 'ran', 'run', 'running', 'jog', 'jogged',
      'jogging', 'cardio', 'lift', 'lifted', 'lifting', 'weights',
      'cycled', 'cycling', 'biked', 'biking', 'yoga', 'swam', 'swim',
      'swimming', 'hike', 'hiked', 'hiking', 'basketball', 'soccer',
      'football', 'tennis', 'boxing', 'kickboxing', 'pilates',
      'trained', 'training', 'squats', 'deadlifts', 'bench', 'push day',
      'pull day', 'leg day', 'chest day', 'arm day',
    ],
  },
];
